[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI=false npm run build"
  publish = "dist"
  base = "client/home-rental-booking"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force" 